authors:
  depictio-team:
    name: Depictio Team
    description: The core development team behind Depictio
    avatar: https://github.com/depictio.png
    url: https://github.com/depictio
  thomas-weber:
    name: Thomas Weber
    description: Lead Developer & Founder
    avatar: https://github.com/thomasly5.png
    url: https://github.com/thomasly5