name: Sync Docs Version With Main Repo

on:
  repository_dispatch:
    types: [new-release]

jobs:
  deploy-docs-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Update pyproject.toml version
        run: |
          VERSION="${{ github.event.client_payload.version }}"
          # Use sed to update version in pyproject.toml
          sed -i 's/^version = \".*\"/version = \"'$VERSION'\"/' pyproject.toml

      - name: Install dependencies
        run: pip install mike mkdocs

      - name: Deploy docs with mike
        run: |
          mike deploy ${{ github.event.client_payload.version }} latest
          mike set-default latest

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml
          git commit -m "Update docs version to ${{ github.event.client_payload.version }}"
          git push
